// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  key: __t.string(),
  identity: __t.identity(),
  name: __t.string(),
  course: __t.string(),
  finished: __t.bool(),
  timeMs: __t.u32().name("time_ms"),
  gatesHit: __t.u16().name("gates_hit"),
  gatesTotal: __t.u16().name("gates_total"),
  maxSpeed: __t.f32().name("max_speed"),
  distanceM: __t.f32().name("distance_m"),
  samples: __t.u32(),
  splits: __t.array(__t.u32()),
  startedAt: __t.timestamp().name("started_at"),
  finishedAt: __t.timestamp().name("finished_at"),
});
