// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateChallengeReducer from "../create_challenge_reducer";
import FinishRunReducer from "../finish_run_reducer";
import JoinReducer from "../join_reducer";
import LinkCodeReducer from "../link_code_reducer";
import MarkSentReducer from "../mark_sent_reducer";
import PushPhotoReducer from "../push_photo_reducer";
import PushTraceReducer from "../push_trace_reducer";
import PushVitalsReducer from "../push_vitals_reducer";
import SendCheerReducer from "../send_cheer_reducer";
import SetStateReducer from "../set_state_reducer";
import StartRunReducer from "../start_run_reducer";

export type CreateChallengeParams = __Infer<typeof CreateChallengeReducer>;
export type FinishRunParams = __Infer<typeof FinishRunReducer>;
export type JoinParams = __Infer<typeof JoinReducer>;
export type LinkCodeParams = __Infer<typeof LinkCodeReducer>;
export type MarkSentParams = __Infer<typeof MarkSentReducer>;
export type PushPhotoParams = __Infer<typeof PushPhotoReducer>;
export type PushTraceParams = __Infer<typeof PushTraceReducer>;
export type PushVitalsParams = __Infer<typeof PushVitalsReducer>;
export type SendCheerParams = __Infer<typeof SendCheerReducer>;
export type SetStateParams = __Infer<typeof SetStateReducer>;
export type StartRunParams = __Infer<typeof StartRunReducer>;

