// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  fromName: __t.string().name("from_name"),
  toName: __t.string().name("to_name"),
  course: __t.string(),
  targetTimeMs: __t.u32().name("target_time_ms"),
  status: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
