// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  key: __t.string(),
  joinCode: __t.string().name("join_code"),
  placement: __t.string(),
  startedS: __t.f64().name("started_s"),
  endedS: __t.f64().name("ended_s"),
  distanceM: __t.f32().name("distance_m"),
  climbM: __t.f32().name("climb_m"),
  trail: __t.string(),
  sacScale: __t.string().name("sac_scale"),
  surface: __t.string(),
  motionSamples: __t.u32().name("motion_samples"),
  rateHz: __t.f32().name("rate_hz"),
  gaps: __t.u32(),
  gapS: __t.f32().name("gap_s"),
  cadenceSpm: __t.f32().name("cadence_spm"),
  notes: __t.array(__t.string()),
  at: __t.timestamp(),
});
