// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  tenant: __t.string(),
  keyPrefix: __t.string().name("key_prefix"),
  policyId: __t.string().name("policy_id"),
  route: __t.string(),
  status: __t.u16(),
  ms: __t.f32(),
  at: __t.timestamp(),
});
