// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  handle: __t.string().primaryKey(),
  tenant: __t.string(),
  code: __t.string(),
  name: __t.string(),
  optedOut: __t.bool().name("opted_out"),
  pendingLabel: __t.string().name("pending_label"),
  pendingDelete: __t.bool().name("pending_delete"),
  invites: __t.u32(),
  notes: __t.array(__t.string()),
  consentVersion: __t.string().name("consent_version"),
  consentedAt: __t.timestamp().name("consented_at"),
  firstSeen: __t.timestamp().name("first_seen"),
  lastSeen: __t.timestamp().name("last_seen"),
});
