// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  tenant: __t.string(),
  courseId: __t.string().name("course_id"),
  kind: __t.string(),
  columns: __t.array(__t.string()),
  units: __t.array(__t.string()),
  count: __t.u32(),
  source: __t.string(),
  license: __t.string(),
  meta: __t.string(),
  updatedAt: __t.timestamp().name("updated_at"),
});
