// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  tenant: __t.string(),
  name: __t.string(),
  activity: __t.string(),
  robot: __t.string(),
  description: __t.string(),
  courses: __t.array(__t.string()),
  terrains: __t.array(__t.string()),
  recordings: __t.array(__t.string()),
  referencePoses: __t.array(__t.string()).name("reference_poses"),
  meta: __t.string(),
  updatedAt: __t.timestamp().name("updated_at"),
});
