// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  LatLon,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  key: __t.string(),
  network: __t.string(),
  tenant: __t.string(),
  osm: __t.string(),
  name: __t.string(),
  highway: __t.string(),
  surface: __t.string(),
  sacScale: __t.string().name("sac_scale"),
  area: __t.string(),
  lengthM: __t.f32().name("length_m"),
  climbM: __t.f32().name("climb_m"),
  descentM: __t.f32().name("descent_m"),
  maxGradeDeg: __t.f32().name("max_grade_deg"),
  get path() {
    return __t.array(LatLon);
  },
  profileStepM: __t.f32().name("profile_step_m"),
  profile: __t.array(__t.f32()),
  tags: __t.string(),
});
