// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  tenant: __t.string(),
  policyId: __t.string().name("policy_id"),
  trainingSet: __t.string().name("training_set"),
  hardware: __t.string(),
  status: __t.string(),
  iterations: __t.u32(),
  checkpoint: __t.string(),
  metrics: __t.string(),
  benchmark: __t.string(),
  notes: __t.string(),
  startedAt: __t.timestamp().name("started_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
