// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  key: __t.string().primaryKey(),
  tenant: __t.string(),
  source: __t.string(),
  activity: __t.string(),
  ref: __t.string(),
  uri: __t.string(),
  channels: __t.array(__t.string()),
  units: __t.array(__t.string()),
  rateHz: __t.f32().name("rate_hz"),
  frames: __t.u64(),
  chunks: __t.u32(),
  title: __t.string(),
  license: __t.string(),
  meta: __t.string(),
  writer: __t.identity(),
  closed: __t.bool(),
  startedAt: __t.timestamp().name("started_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
