// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  tenant: __t.string(),
  name: __t.string(),
  place: __t.string(),
  kind: __t.string(),
  centerLat: __t.f64().name("center_lat"),
  centerLon: __t.f64().name("center_lon"),
  radiusM: __t.f32().name("radius_m"),
  ways: __t.u32(),
  lengthKm: __t.f32().name("length_km"),
  areas: __t.u32(),
  sources: __t.string(),
  meta: __t.string(),
  updatedAt: __t.timestamp().name("updated_at"),
});
