// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  LinePoint,
  Gate,
} from "./types";


export default __t.row({
  id: __t.string().primaryKey(),
  tenant: __t.string(),
  resortId: __t.string().name("resort_id"),
  name: __t.string(),
  activity: __t.string(),
  difficulty: __t.string(),
  lengthM: __t.f32().name("length_m"),
  dropM: __t.f32().name("drop_m"),
  meanSlopeDeg: __t.f32().name("mean_slope_deg"),
  maxSlopeDeg: __t.f32().name("max_slope_deg"),
  originLat: __t.f64().name("origin_lat"),
  originLon: __t.f64().name("origin_lon"),
  zDatumMsl: __t.f32().name("z_datum_msl"),
  get line() {
    return __t.array(LinePoint);
  },
  get fullRun() {
    return __t.array(LinePoint).name("full_run");
  },
  get gates() {
    return __t.array(Gate);
  },
  startPose: __t.string().name("start_pose"),
  scene: __t.string(),
  stats: __t.string(),
  source: __t.string(),
  license: __t.string(),
  updatedAt: __t.timestamp().name("updated_at"),
});
