// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  tenant: __t.string(),
  courseId: __t.string(),
  layer: __t.string(),
  nx: __t.u32(),
  ny: __t.u32(),
  cellM: __t.f32(),
  x0: __t.f32(),
  y0: __t.f32(),
  zMin: __t.f32(),
  zMax: __t.f32(),
  source: __t.string(),
  license: __t.string(),
  meta: __t.string(),
};
