// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  key: __t.string(),
  joinCode: __t.string(),
  placement: __t.string(),
  startedS: __t.f64(),
  endedS: __t.f64(),
  distanceM: __t.f32(),
  climbM: __t.f32(),
  trail: __t.string(),
  sacScale: __t.string(),
  surface: __t.string(),
  motionSamples: __t.u32(),
  rateHz: __t.f32(),
  gaps: __t.u32(),
  gapS: __t.f32(),
  cadenceSpm: __t.f32(),
  message: __t.string(),
};
