// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  heading: __t.f32(),
  speed: __t.f32(),
  lean: __t.f32(),
  crouch: __t.f32(),
  air: __t.bool(),
  phase: __t.u8(),
  progress: __t.f32(),
};
