// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  PoseSample,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  runKey: __t.string().name("run_key"),
  seq: __t.u32(),
  get samples() {
    return __t.array(PoseSample);
  },
});
