// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Challenge = __t.object("Challenge", {
  id: __t.u64(),
  fromName: __t.string(),
  toName: __t.string(),
  course: __t.string(),
  targetTimeMs: __t.u32(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type Challenge = __Infer<typeof Challenge>;

export const Cheer = __t.object("Cheer", {
  fromName: __t.string(),
  toName: __t.string(),
  kind: __t.string(),
  at: __t.timestamp(),
});
export type Cheer = __Infer<typeof Cheer>;

export const DatasetStats = __t.object("DatasetStats", {
  id: __t.u8(),
  samples: __t.u64(),
  runs: __t.u64(),
  meters: __t.f64(),
  skiers: __t.u32(),
});
export type DatasetStats = __Infer<typeof DatasetStats>;

export const Feed = __t.object("Feed", {
  id: __t.u64(),
  kind: __t.string(),
  text: __t.string(),
  at: __t.timestamp(),
});
export type Feed = __Infer<typeof Feed>;

export const Outbox = __t.object("Outbox", {
  id: __t.u64(),
  joinCode: __t.string(),
  kind: __t.string(),
  body: __t.string(),
  ref: __t.string(),
  sent: __t.bool(),
  createdAt: __t.timestamp(),
});
export type Outbox = __Infer<typeof Outbox>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  color: __t.u32(),
  joinCode: __t.string(),
  online: __t.bool(),
  runs: __t.u32(),
  bestTimeMs: __t.u32(),
  cheers: __t.u32(),
  lastSeen: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

export const PoseSample = __t.object("PoseSample", {
  tMs: __t.u32(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  speed: __t.f32(),
  heading: __t.f32(),
  lean: __t.f32(),
  crouch: __t.f32(),
  kneeL: __t.f32(),
  kneeR: __t.f32(),
  slopeDeg: __t.f32(),
});
export type PoseSample = __Infer<typeof PoseSample>;

export const Run = __t.object("Run", {
  id: __t.u64(),
  key: __t.string(),
  identity: __t.identity(),
  name: __t.string(),
  course: __t.string(),
  finished: __t.bool(),
  timeMs: __t.u32(),
  gatesHit: __t.u16(),
  gatesTotal: __t.u16(),
  maxSpeed: __t.f32(),
  distanceM: __t.f32(),
  samples: __t.u32(),
  splits: __t.array(__t.u32()),
  startedAt: __t.timestamp(),
  finishedAt: __t.timestamp(),
});
export type Run = __Infer<typeof Run>;

export const RunPhoto = __t.object("RunPhoto", {
  runKey: __t.string(),
  jpeg: __t.string(),
  at: __t.timestamp(),
});
export type RunPhoto = __Infer<typeof RunPhoto>;

export const Skier = __t.object("Skier", {
  identity: __t.identity(),
  name: __t.string(),
  color: __t.u32(),
  course: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  heading: __t.f32(),
  speed: __t.f32(),
  lean: __t.f32(),
  crouch: __t.f32(),
  air: __t.bool(),
  phase: __t.u8(),
  progress: __t.f32(),
  updatedAt: __t.timestamp(),
});
export type Skier = __Infer<typeof Skier>;

export const TickTimer = __t.object("TickTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TickTimer = __Infer<typeof TickTimer>;

export const TraceChunk = __t.object("TraceChunk", {
  id: __t.u64(),
  runKey: __t.string(),
  seq: __t.u32(),
  get samples() {
    return __t.array(PoseSample);
  },
});
export type TraceChunk = __Infer<typeof TraceChunk>;

export const VitalChunk = __t.object("VitalChunk", {
  id: __t.u64(),
  runKey: __t.string(),
  course: __t.string(),
  name: __t.string(),
  restHr: __t.f32(),
  get samples() {
    return __t.array(VitalSample);
  },
  at: __t.timestamp(),
});
export type VitalChunk = __Infer<typeof VitalChunk>;

export const VitalSample = __t.object("VitalSample", {
  tMs: __t.u32(),
  x: __t.f32(),
  y: __t.f32(),
  s: __t.f32(),
  hr: __t.f32(),
  br: __t.f32(),
  rise: __t.f32(),
});
export type VitalSample = __Infer<typeof VitalSample>;

