// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Capture = __t.object("Capture", {
  id: __t.u64(),
  key: __t.string(),
  owner: __t.identity(),
  source: __t.string(),
  activity: __t.string(),
  joinCode: __t.string(),
  ref: __t.string(),
  uri: __t.string(),
  channels: __t.array(__t.string()),
  rateHz: __t.f32(),
  meta: __t.string(),
  frames: __t.u64(),
  chunks: __t.u32(),
  closed: __t.bool(),
  startedAt: __t.timestamp(),
  endedAt: __t.timestamp(),
});
export type Capture = __Infer<typeof Capture>;

export const CaptureChunk = __t.object("CaptureChunk", {
  id: __t.u64(),
  captureKey: __t.string(),
  seq: __t.u32(),
  t0Ms: __t.u64(),
  tMs: __t.array(__t.u32()),
  data: __t.array(__t.f32()),
});
export type CaptureChunk = __Infer<typeof CaptureChunk>;

export const CaptureStats = __t.object("CaptureStats", {
  key: __t.string(),
  captures: __t.u64(),
  frames: __t.u64(),
  values: __t.u64(),
});
export type CaptureStats = __Infer<typeof CaptureStats>;

export const Challenge = __t.object("Challenge", {
  id: __t.u64(),
  fromName: __t.string(),
  toName: __t.string(),
  course: __t.string(),
  targetTimeMs: __t.u32(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type Challenge = __Infer<typeof Challenge>;

export const Cheer = __t.object("Cheer", {
  fromName: __t.string(),
  toName: __t.string(),
  kind: __t.string(),
  at: __t.timestamp(),
});
export type Cheer = __Infer<typeof Cheer>;

export const DatasetStats = __t.object("DatasetStats", {
  id: __t.u8(),
  samples: __t.u64(),
  runs: __t.u64(),
  meters: __t.f64(),
  skiers: __t.u32(),
});
export type DatasetStats = __Infer<typeof DatasetStats>;

export const Feed = __t.object("Feed", {
  id: __t.u64(),
  kind: __t.string(),
  text: __t.string(),
  at: __t.timestamp(),
});
export type Feed = __Infer<typeof Feed>;

export const Hike = __t.object("Hike", {
  id: __t.u64(),
  key: __t.string(),
  joinCode: __t.string(),
  placement: __t.string(),
  startedS: __t.f64(),
  endedS: __t.f64(),
  distanceM: __t.f32(),
  climbM: __t.f32(),
  trail: __t.string(),
  sacScale: __t.string(),
  surface: __t.string(),
  motionSamples: __t.u32(),
  rateHz: __t.f32(),
  gaps: __t.u32(),
  gapS: __t.f32(),
  cadenceSpm: __t.f32(),
  notes: __t.array(__t.string()),
  at: __t.timestamp(),
});
export type Hike = __Infer<typeof Hike>;

export const HikeChunk = __t.object("HikeChunk", {
  id: __t.u64(),
  hikeKey: __t.string(),
  seq: __t.u32(),
  get samples() {
    return __t.array(HikeSample);
  },
});
export type HikeChunk = __Infer<typeof HikeChunk>;

export const HikeSample = __t.object("HikeSample", {
  tS: __t.u32(),
  lat: __t.f64(),
  lon: __t.f64(),
  altM: __t.f32(),
  speed: __t.f32(),
  slopeDeg: __t.f32(),
  cadence: __t.f32(),
  bounce: __t.f32(),
  impact: __t.f32(),
});
export type HikeSample = __Infer<typeof HikeSample>;

export const HikeStats = __t.object("HikeStats", {
  id: __t.u8(),
  hikes: __t.u64(),
  meters: __t.f64(),
  seconds: __t.f64(),
  motionSamples: __t.u64(),
  hikers: __t.u32(),
});
export type HikeStats = __Infer<typeof HikeStats>;

export const HikeWriter = __t.object("HikeWriter", {
  id: __t.u8(),
  writer: __t.identity(),
});
export type HikeWriter = __Infer<typeof HikeWriter>;

export const Outbox = __t.object("Outbox", {
  id: __t.u64(),
  joinCode: __t.string(),
  kind: __t.string(),
  body: __t.string(),
  ref: __t.string(),
  sent: __t.bool(),
  createdAt: __t.timestamp(),
});
export type Outbox = __Infer<typeof Outbox>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  color: __t.u32(),
  joinCode: __t.string(),
  online: __t.bool(),
  runs: __t.u32(),
  bestTimeMs: __t.u32(),
  cheers: __t.u32(),
  lastSeen: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

export const PoseSample = __t.object("PoseSample", {
  tMs: __t.u32(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  speed: __t.f32(),
  heading: __t.f32(),
  lean: __t.f32(),
  crouch: __t.f32(),
  kneeL: __t.f32(),
  kneeR: __t.f32(),
  slopeDeg: __t.f32(),
});
export type PoseSample = __Infer<typeof PoseSample>;

export const Run = __t.object("Run", {
  id: __t.u64(),
  key: __t.string(),
  identity: __t.identity(),
  name: __t.string(),
  course: __t.string(),
  finished: __t.bool(),
  timeMs: __t.u32(),
  gatesHit: __t.u16(),
  gatesTotal: __t.u16(),
  maxSpeed: __t.f32(),
  distanceM: __t.f32(),
  samples: __t.u32(),
  splits: __t.array(__t.u32()),
  startedAt: __t.timestamp(),
  finishedAt: __t.timestamp(),
});
export type Run = __Infer<typeof Run>;

export const RunPhoto = __t.object("RunPhoto", {
  runKey: __t.string(),
  jpeg: __t.string(),
  at: __t.timestamp(),
});
export type RunPhoto = __Infer<typeof RunPhoto>;

export const Skier = __t.object("Skier", {
  identity: __t.identity(),
  name: __t.string(),
  color: __t.u32(),
  course: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  heading: __t.f32(),
  speed: __t.f32(),
  lean: __t.f32(),
  crouch: __t.f32(),
  air: __t.bool(),
  phase: __t.u8(),
  progress: __t.f32(),
  updatedAt: __t.timestamp(),
});
export type Skier = __Infer<typeof Skier>;

export const TickTimer = __t.object("TickTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TickTimer = __Infer<typeof TickTimer>;

export const TraceChunk = __t.object("TraceChunk", {
  id: __t.u64(),
  runKey: __t.string(),
  seq: __t.u32(),
  get samples() {
    return __t.array(PoseSample);
  },
});
export type TraceChunk = __Infer<typeof TraceChunk>;

