// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  tenant: __t.string(),
  name: __t.string(),
  robot: __t.string(),
  skill: __t.string(),
  obsDim: __t.u32(),
  actionDim: __t.u32(),
  controlHz: __t.f32(),
  runtime: __t.string(),
  endpoint: __t.string(),
  trainingSet: __t.string(),
  benchmark: __t.string(),
  spec: __t.string(),
};
