// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  LinePoint,
  Gate,
} from "./types";

export default {
  id: __t.string(),
  tenant: __t.string(),
  resortId: __t.string(),
  name: __t.string(),
  activity: __t.string(),
  difficulty: __t.string(),
  lengthM: __t.f32(),
  dropM: __t.f32(),
  meanSlopeDeg: __t.f32(),
  maxSlopeDeg: __t.f32(),
  originLat: __t.f64(),
  originLon: __t.f64(),
  zDatumMsl: __t.f32(),
  get line() {
    return __t.array(LinePoint);
  },
  get fullRun() {
    return __t.array(LinePoint);
  },
  get gates() {
    return __t.array(Gate);
  },
  startPose: __t.string(),
  scene: __t.string(),
  stats: __t.string(),
  source: __t.string(),
  license: __t.string(),
};
