// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  VitalSample,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  runKey: __t.string().name("run_key"),
  course: __t.string(),
  name: __t.string(),
  restHr: __t.f32().name("rest_hr"),
  get samples() {
    return __t.array(VitalSample);
  },
  at: __t.timestamp(),
});
