// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  key: __t.string(),
  owner: __t.identity(),
  source: __t.string(),
  activity: __t.string(),
  joinCode: __t.string().name("join_code"),
  ref: __t.string(),
  uri: __t.string(),
  channels: __t.array(__t.string()),
  rateHz: __t.f32().name("rate_hz"),
  meta: __t.string(),
  frames: __t.u64(),
  chunks: __t.u32(),
  closed: __t.bool(),
  startedAt: __t.timestamp().name("started_at"),
  endedAt: __t.timestamp().name("ended_at"),
});
