// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.2 (commit 58d2a40718c59535fd5c267e836d473298eb84d5).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddApiKeyReducer from "./add_api_key_reducer";
import AddMemberIdentityReducer from "./add_member_identity_reducer";
import AddPlatformServiceReducer from "./add_platform_service_reducer";
import ClaimHikeWriterReducer from "./claim_hike_writer_reducer";
import ClaimPlatformAdminReducer from "./claim_platform_admin_reducer";
import CloseCaptureReducer from "./close_capture_reducer";
import CloseRecordingReducer from "./close_recording_reducer";
import CreateChallengeReducer from "./create_challenge_reducer";
import CreateInviteReducer from "./create_invite_reducer";
import CreateTenantReducer from "./create_tenant_reducer";
import DeleteAppUserReducer from "./delete_app_user_reducer";
import DeleteHikesReducer from "./delete_hikes_reducer";
import DeleteItemReducer from "./delete_item_reducer";
import FinishRunReducer from "./finish_run_reducer";
import JoinReducer from "./join_reducer";
import LabelHikeReducer from "./label_hike_reducer";
import LinkCodeReducer from "./link_code_reducer";
import LogApiCallsReducer from "./log_api_calls_reducer";
import MarkSentReducer from "./mark_sent_reducer";
import OpenCaptureReducer from "./open_capture_reducer";
import PushAreasReducer from "./push_areas_reducer";
import PushCaptureChunkReducer from "./push_capture_chunk_reducer";
import PushHikeChunkReducer from "./push_hike_chunk_reducer";
import PushPhotoReducer from "./push_photo_reducer";
import PushPointsReducer from "./push_points_reducer";
import PushRecordingChunkReducer from "./push_recording_chunk_reducer";
import PushSegmentsReducer from "./push_segments_reducer";
import PushTerrainRowsReducer from "./push_terrain_rows_reducer";
import PushTraceReducer from "./push_trace_reducer";
import PushTrailsReducer from "./push_trails_reducer";
import PutPointSetReducer from "./put_point_set_reducer";
import PutRecordingReducer from "./put_recording_reducer";
import PutTerrainReducer from "./put_terrain_reducer";
import RecordHikeReducer from "./record_hike_reducer";
import RedeemInviteReducer from "./redeem_invite_reducer";
import RemoveMemberReducer from "./remove_member_reducer";
import RemovePlatformServiceReducer from "./remove_platform_service_reducer";
import RevokeApiKeyReducer from "./revoke_api_key_reducer";
import RevokeInviteReducer from "./revoke_invite_reducer";
import SendCheerReducer from "./send_cheer_reducer";
import SetActiveTenantReducer from "./set_active_tenant_reducer";
import SetMemberRoleReducer from "./set_member_role_reducer";
import SetProfileReducer from "./set_profile_reducer";
import SetStateReducer from "./set_state_reducer";
import StartRunReducer from "./start_run_reducer";
import UpdateTenantReducer from "./update_tenant_reducer";
import UpsertAppInviteReducer from "./upsert_app_invite_reducer";
import UpsertAppMessageReducer from "./upsert_app_message_reducer";
import UpsertAppSessionReducer from "./upsert_app_session_reducer";
import UpsertAppUserReducer from "./upsert_app_user_reducer";
import UpsertCourseReducer from "./upsert_course_reducer";
import UpsertEvaluationReducer from "./upsert_evaluation_reducer";
import UpsertPolicyReducer from "./upsert_policy_reducer";
import UpsertReferencePoseReducer from "./upsert_reference_pose_reducer";
import UpsertResortReducer from "./upsert_resort_reducer";
import UpsertTrailNetworkReducer from "./upsert_trail_network_reducer";
import UpsertTrainRunReducer from "./upsert_train_run_reducer";
import UpsertTrainingSetReducer from "./upsert_training_set_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import CaptureRow from "./capture_table";
import CaptureChunkRow from "./capture_chunk_table";
import CaptureStatsRow from "./capture_stats_table";
import ChallengeRow from "./challenge_table";
import CheerRow from "./cheer_table";
import DatasetStatsRow from "./dataset_stats_table";
import FeedRow from "./feed_table";
import HikeRow from "./hike_table";
import HikeChunkRow from "./hike_chunk_table";
import HikeStatsRow from "./hike_stats_table";
import MyAccountRow from "./my_account_table";
import MyApiCallViewRow from "./my_api_call_view_table";
import MyApiKeyViewRow from "./my_api_key_view_table";
import MyAppInviteViewRow from "./my_app_invite_view_table";
import MyAppMessageViewRow from "./my_app_message_view_table";
import MyAppSessionViewRow from "./my_app_session_view_table";
import MyAppUserViewRow from "./my_app_user_view_table";
import MyAreaViewRow from "./my_area_view_table";
import MyCourseViewRow from "./my_course_view_table";
import MyEvaluationViewRow from "./my_evaluation_view_table";
import MyInviteRow from "./my_invite_table";
import MyMemberRow from "./my_member_table";
import MyPointChunkViewRow from "./my_point_chunk_view_table";
import MyPointSetViewRow from "./my_point_set_view_table";
import MyPolicyViewRow from "./my_policy_view_table";
import MyRecordingChunkViewRow from "./my_recording_chunk_view_table";
import MyRecordingViewRow from "./my_recording_view_table";
import MyReferencePoseViewRow from "./my_reference_pose_view_table";
import MyResortViewRow from "./my_resort_view_table";
import MySegmentViewRow from "./my_segment_view_table";
import MyTenantRow from "./my_tenant_table";
import MyTerrainChunkViewRow from "./my_terrain_chunk_view_table";
import MyTerrainViewRow from "./my_terrain_view_table";
import MyTrailNetworkViewRow from "./my_trail_network_view_table";
import MyTrailViewRow from "./my_trail_view_table";
import MyTrainRunViewRow from "./my_train_run_view_table";
import MyTrainingSetViewRow from "./my_training_set_view_table";
import OutboxRow from "./outbox_table";
import PlayerRow from "./player_table";
import PublicApiCallViewRow from "./public_api_call_view_table";
import PublicAreaViewRow from "./public_area_view_table";
import PublicCourseViewRow from "./public_course_view_table";
import PublicEvaluationViewRow from "./public_evaluation_view_table";
import PublicPointChunkViewRow from "./public_point_chunk_view_table";
import PublicPointSetViewRow from "./public_point_set_view_table";
import PublicPolicyViewRow from "./public_policy_view_table";
import PublicRecordingChunkViewRow from "./public_recording_chunk_view_table";
import PublicRecordingViewRow from "./public_recording_view_table";
import PublicReferencePoseViewRow from "./public_reference_pose_view_table";
import PublicResortViewRow from "./public_resort_view_table";
import PublicSegmentViewRow from "./public_segment_view_table";
import PublicTenantRow from "./public_tenant_table";
import PublicTerrainChunkViewRow from "./public_terrain_chunk_view_table";
import PublicTerrainViewRow from "./public_terrain_view_table";
import PublicTrailNetworkViewRow from "./public_trail_network_view_table";
import PublicTrailViewRow from "./public_trail_view_table";
import PublicTrainRunViewRow from "./public_train_run_view_table";
import PublicTrainingSetViewRow from "./public_training_set_view_table";
import RunRow from "./run_table";
import RunPhotoRow from "./run_photo_table";
import ServiceApiKeyViewRow from "./service_api_key_view_table";
import SkierRow from "./skier_table";
import TraceChunkRow from "./trace_chunk_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  capture: __table({
    name: 'capture',
    indexes: [
      { accessor: 'activity', name: 'capture_activity_idx_btree', algorithm: 'btree', columns: [
        'activity',
      ] },
      { accessor: 'id', name: 'capture_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'joinCode', name: 'capture_join_code_idx_btree', algorithm: 'btree', columns: [
        'joinCode',
      ] },
      { accessor: 'key', name: 'capture_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
      { accessor: 'source', name: 'capture_source_idx_btree', algorithm: 'btree', columns: [
        'source',
      ] },
    ],
    constraints: [
      { name: 'capture_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'capture_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, CaptureRow),
  captureChunk: __table({
    name: 'capture_chunk',
    indexes: [
      { accessor: 'captureKey', name: 'capture_chunk_capture_key_idx_btree', algorithm: 'btree', columns: [
        'captureKey',
      ] },
      { accessor: 'id', name: 'capture_chunk_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'capture_chunk_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CaptureChunkRow),
  captureStats: __table({
    name: 'capture_stats',
    indexes: [
      { accessor: 'key', name: 'capture_stats_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'capture_stats_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, CaptureStatsRow),
  challenge: __table({
    name: 'challenge',
    indexes: [
      { accessor: 'id', name: 'challenge_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'toName', name: 'challenge_to_name_idx_btree', algorithm: 'btree', columns: [
        'toName',
      ] },
    ],
    constraints: [
      { name: 'challenge_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ChallengeRow),
  cheer: __table({
    name: 'cheer',
    indexes: [
    ],
    constraints: [
    ],
    event: true,
  }, CheerRow),
  datasetStats: __table({
    name: 'dataset_stats',
    indexes: [
      { accessor: 'id', name: 'dataset_stats_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'dataset_stats_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DatasetStatsRow),
  feed: __table({
    name: 'feed',
    indexes: [
      { accessor: 'id', name: 'feed_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'feed_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, FeedRow),
  hike: __table({
    name: 'hike',
    indexes: [
      { accessor: 'id', name: 'hike_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'joinCode', name: 'hike_join_code_idx_btree', algorithm: 'btree', columns: [
        'joinCode',
      ] },
      { accessor: 'key', name: 'hike_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'hike_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'hike_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, HikeRow),
  hikeChunk: __table({
    name: 'hike_chunk',
    indexes: [
      { accessor: 'hikeKey', name: 'hike_chunk_hike_key_idx_btree', algorithm: 'btree', columns: [
        'hikeKey',
      ] },
      { accessor: 'id', name: 'hike_chunk_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'hike_chunk_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, HikeChunkRow),
  hikeStats: __table({
    name: 'hike_stats',
    indexes: [
      { accessor: 'id', name: 'hike_stats_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'hike_stats_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, HikeStatsRow),
  outbox: __table({
    name: 'outbox',
    indexes: [
      { accessor: 'id', name: 'outbox_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'sent', name: 'outbox_sent_idx_btree', algorithm: 'btree', columns: [
        'sent',
      ] },
    ],
    constraints: [
      { name: 'outbox_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, OutboxRow),
  player: __table({
    name: 'player',
    indexes: [
      { accessor: 'identity', name: 'player_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'joinCode', name: 'player_join_code_idx_btree', algorithm: 'btree', columns: [
        'joinCode',
      ] },
    ],
    constraints: [
      { name: 'player_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerRow),
  run: __table({
    name: 'run',
    indexes: [
      { accessor: 'finished', name: 'run_finished_idx_btree', algorithm: 'btree', columns: [
        'finished',
      ] },
      { accessor: 'id', name: 'run_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'identity', name: 'run_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'key', name: 'run_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'run_id_key', constraint: 'unique', columns: ['id'] },
      { name: 'run_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, RunRow),
  runPhoto: __table({
    name: 'run_photo',
    indexes: [
      { accessor: 'runKey', name: 'run_photo_run_key_idx_btree', algorithm: 'btree', columns: [
        'runKey',
      ] },
    ],
    constraints: [
      { name: 'run_photo_run_key_key', constraint: 'unique', columns: ['runKey'] },
    ],
  }, RunPhotoRow),
  skier: __table({
    name: 'skier',
    indexes: [
      { accessor: 'identity', name: 'skier_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'skier_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, SkierRow),
  traceChunk: __table({
    name: 'trace_chunk',
    indexes: [
      { accessor: 'id', name: 'trace_chunk_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'runKey', name: 'trace_chunk_run_key_idx_btree', algorithm: 'btree', columns: [
        'runKey',
      ] },
    ],
    constraints: [
      { name: 'trace_chunk_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TraceChunkRow),
  myAccount: __table({
    name: 'my_account',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAccountRow),
  myApiCallView: __table({
    name: 'my_api_call',
    indexes: [
    ],
    constraints: [
    ],
  }, MyApiCallViewRow),
  myApiKeyView: __table({
    name: 'my_api_key',
    indexes: [
    ],
    constraints: [
    ],
  }, MyApiKeyViewRow),
  myAppInviteView: __table({
    name: 'my_app_invite',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAppInviteViewRow),
  myAppMessageView: __table({
    name: 'my_app_message',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAppMessageViewRow),
  myAppSessionView: __table({
    name: 'my_app_session',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAppSessionViewRow),
  myAppUserView: __table({
    name: 'my_app_user',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAppUserViewRow),
  myAreaView: __table({
    name: 'my_area',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAreaViewRow),
  myCourseView: __table({
    name: 'my_course',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCourseViewRow),
  myEvaluationView: __table({
    name: 'my_evaluation',
    indexes: [
    ],
    constraints: [
    ],
  }, MyEvaluationViewRow),
  myInvite: __table({
    name: 'my_invite',
    indexes: [
    ],
    constraints: [
    ],
  }, MyInviteRow),
  myMember: __table({
    name: 'my_member',
    indexes: [
    ],
    constraints: [
    ],
  }, MyMemberRow),
  myPointChunkView: __table({
    name: 'my_point_chunk',
    indexes: [
    ],
    constraints: [
    ],
  }, MyPointChunkViewRow),
  myPointSetView: __table({
    name: 'my_point_set',
    indexes: [
    ],
    constraints: [
    ],
  }, MyPointSetViewRow),
  myPolicyView: __table({
    name: 'my_policy',
    indexes: [
    ],
    constraints: [
    ],
  }, MyPolicyViewRow),
  myRecordingView: __table({
    name: 'my_recording',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRecordingViewRow),
  myRecordingChunkView: __table({
    name: 'my_recording_chunk',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRecordingChunkViewRow),
  myReferencePoseView: __table({
    name: 'my_reference_pose',
    indexes: [
    ],
    constraints: [
    ],
  }, MyReferencePoseViewRow),
  myResortView: __table({
    name: 'my_resort',
    indexes: [
    ],
    constraints: [
    ],
  }, MyResortViewRow),
  mySegmentView: __table({
    name: 'my_segment',
    indexes: [
    ],
    constraints: [
    ],
  }, MySegmentViewRow),
  myTenant: __table({
    name: 'my_tenant',
    indexes: [
    ],
    constraints: [
    ],
  }, MyTenantRow),
  myTerrainView: __table({
    name: 'my_terrain',
    indexes: [
    ],
    constraints: [
    ],
  }, MyTerrainViewRow),
  myTerrainChunkView: __table({
    name: 'my_terrain_chunk',
    indexes: [
    ],
    constraints: [
    ],
  }, MyTerrainChunkViewRow),
  myTrailView: __table({
    name: 'my_trail',
    indexes: [
    ],
    constraints: [
    ],
  }, MyTrailViewRow),
  myTrailNetworkView: __table({
    name: 'my_trail_network',
    indexes: [
    ],
    constraints: [
    ],
  }, MyTrailNetworkViewRow),
  myTrainRunView: __table({
    name: 'my_train_run',
    indexes: [
    ],
    constraints: [
    ],
  }, MyTrainRunViewRow),
  myTrainingSetView: __table({
    name: 'my_training_set',
    indexes: [
    ],
    constraints: [
    ],
  }, MyTrainingSetViewRow),
  publicApiCallView: __table({
    name: 'public_api_call',
    indexes: [
    ],
    constraints: [
    ],
  }, PublicApiCallViewRow),
  publicAreaView: __table({
    name: 'public_area',
    indexes: [
    ],
    constraints: [
    ],
  }, PublicAreaViewRow),
  publicCourseView: __table({
    name: 'public_course',
    indexes: [
    ],
    constraints: [
    ],
  }, PublicCourseViewRow),
  publicEvaluationView: __table({
    name: 'public_evaluation',
    indexes: [
    ],
    constraints: [
    ],
  }, PublicEvaluationViewRow),
  publicPointChunkView: __table({
    name: 'public_point_chunk',
    indexes: [
    ],
    constraints: [
    ],
  }, PublicPointChunkViewRow),
  publicPointSetView: __table({
    name: 'public_point_set',
    indexes: [
    ],
    constraints: [
    ],
  }, PublicPointSetViewRow),
  publicPolicyView: __table({
    name: 'public_policy',
    indexes: [
    ],
    constraints: [
    ],
  }, PublicPolicyViewRow),
  publicRecordingView: __table({
    name: 'public_recording',
    indexes: [
    ],
    constraints: [
    ],
  }, PublicRecordingViewRow),
  publicRecordingChunkView: __table({
    name: 'public_recording_chunk',
    indexes: [
    ],
    constraints: [
    ],
  }, PublicRecordingChunkViewRow),
  publicReferencePoseView: __table({
    name: 'public_reference_pose',
    indexes: [
    ],
    constraints: [
    ],
  }, PublicReferencePoseViewRow),
  publicResortView: __table({
    name: 'public_resort',
    indexes: [
    ],
    constraints: [
    ],
  }, PublicResortViewRow),
  publicSegmentView: __table({
    name: 'public_segment',
    indexes: [
    ],
    constraints: [
    ],
  }, PublicSegmentViewRow),
  publicTenant: __table({
    name: 'public_tenant',
    indexes: [
    ],
    constraints: [
    ],
  }, PublicTenantRow),
  publicTerrainView: __table({
    name: 'public_terrain',
    indexes: [
    ],
    constraints: [
    ],
  }, PublicTerrainViewRow),
  publicTerrainChunkView: __table({
    name: 'public_terrain_chunk',
    indexes: [
    ],
    constraints: [
    ],
  }, PublicTerrainChunkViewRow),
  publicTrailView: __table({
    name: 'public_trail',
    indexes: [
    ],
    constraints: [
    ],
  }, PublicTrailViewRow),
  publicTrailNetworkView: __table({
    name: 'public_trail_network',
    indexes: [
    ],
    constraints: [
    ],
  }, PublicTrailNetworkViewRow),
  publicTrainRunView: __table({
    name: 'public_train_run',
    indexes: [
    ],
    constraints: [
    ],
  }, PublicTrainRunViewRow),
  publicTrainingSetView: __table({
    name: 'public_training_set',
    indexes: [
    ],
    constraints: [
    ],
  }, PublicTrainingSetViewRow),
  serviceApiKeyView: __table({
    name: 'service_api_key',
    indexes: [
    ],
    constraints: [
    ],
  }, ServiceApiKeyViewRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_api_key", AddApiKeyReducer),
  __reducerSchema("add_member_identity", AddMemberIdentityReducer),
  __reducerSchema("add_platform_service", AddPlatformServiceReducer),
  __reducerSchema("claim_hike_writer", ClaimHikeWriterReducer),
  __reducerSchema("claim_platform_admin", ClaimPlatformAdminReducer),
  __reducerSchema("close_capture", CloseCaptureReducer),
  __reducerSchema("close_recording", CloseRecordingReducer),
  __reducerSchema("create_challenge", CreateChallengeReducer),
  __reducerSchema("create_invite", CreateInviteReducer),
  __reducerSchema("create_tenant", CreateTenantReducer),
  __reducerSchema("delete_app_user", DeleteAppUserReducer),
  __reducerSchema("delete_hikes", DeleteHikesReducer),
  __reducerSchema("delete_item", DeleteItemReducer),
  __reducerSchema("finish_run", FinishRunReducer),
  __reducerSchema("join", JoinReducer),
  __reducerSchema("label_hike", LabelHikeReducer),
  __reducerSchema("link_code", LinkCodeReducer),
  __reducerSchema("log_api_calls", LogApiCallsReducer),
  __reducerSchema("mark_sent", MarkSentReducer),
  __reducerSchema("open_capture", OpenCaptureReducer),
  __reducerSchema("push_areas", PushAreasReducer),
  __reducerSchema("push_capture_chunk", PushCaptureChunkReducer),
  __reducerSchema("push_hike_chunk", PushHikeChunkReducer),
  __reducerSchema("push_photo", PushPhotoReducer),
  __reducerSchema("push_points", PushPointsReducer),
  __reducerSchema("push_recording_chunk", PushRecordingChunkReducer),
  __reducerSchema("push_segments", PushSegmentsReducer),
  __reducerSchema("push_terrain_rows", PushTerrainRowsReducer),
  __reducerSchema("push_trace", PushTraceReducer),
  __reducerSchema("push_trails", PushTrailsReducer),
  __reducerSchema("put_point_set", PutPointSetReducer),
  __reducerSchema("put_recording", PutRecordingReducer),
  __reducerSchema("put_terrain", PutTerrainReducer),
  __reducerSchema("record_hike", RecordHikeReducer),
  __reducerSchema("redeem_invite", RedeemInviteReducer),
  __reducerSchema("remove_member", RemoveMemberReducer),
  __reducerSchema("remove_platform_service", RemovePlatformServiceReducer),
  __reducerSchema("revoke_api_key", RevokeApiKeyReducer),
  __reducerSchema("revoke_invite", RevokeInviteReducer),
  __reducerSchema("send_cheer", SendCheerReducer),
  __reducerSchema("set_active_tenant", SetActiveTenantReducer),
  __reducerSchema("set_member_role", SetMemberRoleReducer),
  __reducerSchema("set_profile", SetProfileReducer),
  __reducerSchema("set_state", SetStateReducer),
  __reducerSchema("start_run", StartRunReducer),
  __reducerSchema("update_tenant", UpdateTenantReducer),
  __reducerSchema("upsert_app_invite", UpsertAppInviteReducer),
  __reducerSchema("upsert_app_message", UpsertAppMessageReducer),
  __reducerSchema("upsert_app_session", UpsertAppSessionReducer),
  __reducerSchema("upsert_app_user", UpsertAppUserReducer),
  __reducerSchema("upsert_course", UpsertCourseReducer),
  __reducerSchema("upsert_evaluation", UpsertEvaluationReducer),
  __reducerSchema("upsert_policy", UpsertPolicyReducer),
  __reducerSchema("upsert_reference_pose", UpsertReferencePoseReducer),
  __reducerSchema("upsert_resort", UpsertResortReducer),
  __reducerSchema("upsert_trail_network", UpsertTrailNetworkReducer),
  __reducerSchema("upsert_train_run", UpsertTrainRunReducer),
  __reducerSchema("upsert_training_set", UpsertTrainingSetReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.2" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

