// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  key: __t.string(),
  network: __t.string(),
  tenant: __t.string(),
  osm: __t.string(),
  name: __t.string(),
  kind: __t.string(),
  ways: __t.u32(),
  lengthM: __t.f32().name("length_m"),
  geometry: __t.string(),
  stats: __t.string(),
});
