// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  tenant: __t.string(),
  activity: __t.string(),
  phase: __t.string(),
  robot: __t.string(),
  joints: __t.array(__t.string()),
  values: __t.array(__t.f32()),
  frames: __t.u32(),
  human: __t.string(),
  sources: __t.string(),
  updatedAt: __t.timestamp().name("updated_at"),
});
