// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  key: __t.string(),
  source: __t.string(),
  activity: __t.string(),
  joinCode: __t.string(),
  ref: __t.string(),
  uri: __t.string(),
  channels: __t.array(__t.string()),
  rateHz: __t.f32(),
  meta: __t.string(),
};
