// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  name: __t.string(),
  color: __t.u32(),
  joinCode: __t.string().name("join_code"),
  online: __t.bool(),
  runs: __t.u32(),
  bestTimeMs: __t.u32().name("best_time_ms"),
  cheers: __t.u32(),
  lastSeen: __t.timestamp().name("last_seen"),
});
