// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  key: __t.string(),
  recordingKey: __t.string().name("recording_key"),
  tenant: __t.string(),
  kind: __t.string(),
  t0Ms: __t.u64().name("t_0_ms"),
  t1Ms: __t.u64().name("t_1_ms"),
  label: __t.string(),
  meta: __t.string(),
});
