// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  tenant: __t.string(),
  courseId: __t.string().name("course_id"),
  layer: __t.string(),
  nx: __t.u32(),
  ny: __t.u32(),
  cellM: __t.f32().name("cell_m"),
  x0: __t.f32().name("x_0"),
  y0: __t.f32().name("y_0"),
  zMin: __t.f32().name("z_min"),
  zMax: __t.f32().name("z_max"),
  rows: __t.u32(),
  source: __t.string(),
  license: __t.string(),
  meta: __t.string(),
  updatedAt: __t.timestamp().name("updated_at"),
});
