// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  tenant: __t.string(),
  name: __t.string(),
  robot: __t.string(),
  skill: __t.string(),
  obsDim: __t.u32().name("obs_dim"),
  actionDim: __t.u32().name("action_dim"),
  controlHz: __t.f32().name("control_hz"),
  runtime: __t.string(),
  endpoint: __t.string(),
  trainingSet: __t.string().name("training_set"),
  benchmark: __t.string(),
  spec: __t.string(),
  updatedAt: __t.timestamp().name("updated_at"),
});
