// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  tenant: __t.string(),
  name: __t.string(),
  place: __t.string(),
  kind: __t.string(),
  centerLat: __t.f64(),
  centerLon: __t.f64(),
  radiusM: __t.f32(),
  ways: __t.u32(),
  lengthKm: __t.f32(),
  areas: __t.u32(),
  sources: __t.string(),
  meta: __t.string(),
};
