// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  handle: __t.string(),
  tenant: __t.string(),
  code: __t.string(),
  name: __t.string(),
  optedOut: __t.bool(),
  pendingLabel: __t.string(),
  pendingDelete: __t.bool(),
  invites: __t.u32(),
  notes: __t.array(__t.string()),
  firstSeenMs: __t.u64(),
};
