// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  tenant: __t.string(),
  policyId: __t.string(),
  trainingSet: __t.string(),
  hardware: __t.string(),
  status: __t.string(),
  iterations: __t.u32(),
  checkpoint: __t.string(),
  metrics: __t.string(),
  benchmark: __t.string(),
  notes: __t.string(),
  startedAt: __t.timestamp(),
};
